on:
  push:
    # branches:
    #   - main

name: Build and Release Linux App

env:
  BUILD_DIR: build/linux/x64/release/bundle
  ARCHIVE_NAME: musily-linux-x64.tar.gz

jobs:
  build:
    name: Build Linux App
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies required for Linux desktop build
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl git unzip xz-utils zip \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev libglu1-mesa \
            libstdc++-12-dev libmpv-dev \
            libjsoncpp-dev libsecret-1-dev

      # Extract version from pubspec
      - name: Extract version
        id: extract_version
        run: |
          version=$(chmod +x musily_metadata.sh && ./musily_metadata.sh --version)
          echo "version=${version}" >> $GITHUB_ENV
          echo "version=${version}" >> $GITHUB_OUTPUT

      # Extract description from CHANGELOG.md
      - name: Extract description
        id: extract_description
        run: |
          description=$(chmod +x musily_metadata.sh && ./musily_metadata.sh --description)
          escaped_description=$(echo "$description" | sed 's/%/%25/g; s/\r/%0D/g; s/\n/%0A/g; s/\*/\\*/g; s/_/\\_/g')
          echo "description=${escaped_description}" >> $GITHUB_ENV
          echo "description=${escaped_description}" >> $GITHUB_OUTPUT

      # Setup the Flutter environment.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.22.3

      # Build the Linux app
      - name: Build Linux app
        run: flutter build linux --release

      # Create the .tar.gz archive
      - name: Create tar.gz archive
        run: |
          tar -czvf ${{env.ARCHIVE_NAME}} -C ${{env.BUILD_DIR}} .
          echo "Archive created: ${{env.ARCHIVE_NAME}}"

      # Calculate SHA256 checksum
      - name: Calculate SHA256 checksum
        id: sha256_checksum
        run: |
          sha256sum ${{env.ARCHIVE_NAME}} | awk '{print $1}' >> $GITHUB_OUTPUT

      # Release the archive
      - name: Release Linux archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: MusilyApp/musily
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{env.ARCHIVE_NAME}}
          asset_name: ${{env.ARCHIVE_NAME}}
          tag: ${{ steps.extract_version.outputs.version }}
          body: "${{ steps.extract_description.outputs.description }}"
          prerelease: false
          overwrite: true

      # Add SHA256 checksum to release
      - name: Add SHA256 checksum to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: MusilyApp/musily
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{env.ARCHIVE_NAME}}.sha256
          asset_name: ${{env.ARCHIVE_NAME}}.sha256
          tag: ${{ steps.extract_version.outputs.version }}
          body: "${{ steps.extract_description.outputs.description }}"
          prerelease: false
          overwrite: true
